name: notification

on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: echo ${{ github.event.workflow_run.conclusion }}
      - run: echo ${{ github.event.workflow_run.url }}
