name: test

on:
  repository_dispatch:
    types: [trigger-workflow]
  push:
    branches:
      - development
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: githubrepositoryconnector
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '12.x'

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - run: env
